In [2]:
import os
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from google.cloud import bigquery
pd.set_option('display.max_rows', 100)    # Show all rows



load_dotenv()
query_path = os.environ.get('BASE_QUERY_PATH')
client = bigquery.Client(os.environ.get('BIGQUERY_PROJECT_NAME'))

In [3]:
print(os.environ.get('BIGQUERY_PROJECT_NAME'))

phys-439706

In [14]:
# get the types of items that can be administered to a patient

with open(f"{query_path}/fnhrt_temps.sql", 'r') as file:
    FNHRT_read = file.read()

FNHRT_result = client.query(FNHRT_read).to_dataframe()
FNHRT_result

/home/tyx1999120755/.pyenv/versions/3.12.7/envs/transfusion/lib/python3.12/site-packages/google/cloud/bigquery/table.py:1727: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,subject_id,hadm_id,icustay_id,transfusion_starttime,temp_recorded_time,temperature_fahrenheit,baseline_temp_f,fnthr_criteria
0,109,126055,236124,2141-10-17 17:45:00,2141-10-24 05:00:00,100.8,98.7,Temperature ≥38°C (100.4°F)
1,109,158943,243532,2142-03-21 10:45:00,2142-03-21 22:43:00,100.5,NaN,Temperature ≥38°C (100.4°F)
2,109,102024,232807,2142-06-01 21:00:00,2142-06-01 23:00:00,100.8,NaN,Temperature ≥38°C (100.4°F)
3,124,138376,256064,2166-01-11 04:53:00,2166-01-22 08:00:00,100.8,98.1,Temperature ≥38°C (100.4°F)
4,124,138376,256064,2166-01-11 04:53:00,2166-01-19 20:00:00,101.3,98.1,Temperature ≥38°C (100.4°F)
...,...,...,...,...,...,...,...,...
17383,99939,159023,252442,2110-03-22 07:15:00,2110-03-23 08:00:00,100.8,96.4,Temperature ≥38°C (100.4°F)
17384,99939,159023,252442,2110-03-22 07:15:00,2110-03-23 04:00:00,98.5,96.4,Temperature rise ≥1°C (1.8°F) above baseline
17385,99939,159023,252442,2110-03-22 07:15:00,2110-03-23 09:00:00,99.8,96.4,Temperature rise ≥1°C (1.8°F) above baseline
17386,99939,159023,252442,2110-03-22 07:15:00,2110-03-23 10:00:00,99.4,96.4,Temperature rise ≥1°C (1.8°F) above baseline
17387,99939,159023,252442,2110-03-22 07:15:00,2110-03-23 12:00:00,99.3,96.4,Temperature rise ≥1°C (1.8°F) above baseline

In [17]:
#Check unique patients
unique_patients = FNHRT_result.drop_duplicates(subset=['subject_id']).reset_index(drop=True)
len(unique_patients)

1600